version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tic-tac-toe
    volumes:
      - ./data:/var/lib/postgresql/data

  web:
    build: ./web
    restart: always
    ports:
      - 8000:5000
    depends_on:
      - db
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
    volumes:
      - ./web:/app
