version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tic-tac-toe
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  web:
    build: .
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy
    environment:
      FLASK_DEBUG: 1
    # volumes:
    #   - ./web:/app
