"""datetime

Revision ID: 02e1b754c22d
Revises: f282ddbde2a8
Create Date: 2023-06-11 14:34:03.937655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02e1b754c22d'
down_revision = 'f282ddbde2a8'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('game', sa.Column('end_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'end_time')
    op.drop_column('game', 'start_time')
    # ### end Alembic commands ###
