"""game attributes

Revision ID: 0535f157b81a
Revises: 50f7214fd980
Create Date: 2023-06-07 00:04:34.351527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0535f157b81a'
down_revision = '50f7214fd980'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('room_code', sa.String(), nullable=False))
    op.add_column('game', sa.Column('winner', sa.Integer(), nullable=True))
    op.add_column('game', sa.Column('loser', sa.Integer(), nullable=True))
    op.add_column('game', sa.Column('draw', sa.Boolean(), nullable=True))
    op.add_column('game', sa.Column('finished', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'game', ['room_code'])
    op.create_foreign_key(None, 'game', 'player', ['winner'], ['id'])
    op.create_foreign_key(None, 'game', 'player', ['loser'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_constraint(None, 'game', type_='unique')
    op.drop_column('game', 'finished')
    op.drop_column('game', 'draw')
    op.drop_column('game', 'loser')
    op.drop_column('game', 'winner')
    op.drop_column('game', 'room_code')
    # ### end Alembic commands ###
