"""connect game with players

Revision ID: 50f7214fd980
Revises: 44db1da477bc
Create Date: 2023-06-06 23:54:58.305083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50f7214fd980'
down_revision = '44db1da477bc'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('player_1', sa.Integer(), nullable=True))
    op.add_column('game', sa.Column('player_2', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'game', 'player', ['player_1'], ['id'])
    op.create_foreign_key(None, 'game', 'player', ['player_2'], ['id'])
    op.add_column('player', sa.Column('credits', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'credits')
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_column('game', 'player_2')
    op.drop_column('game', 'player_1')
    # ### end Alembic commands ###
