"""player game and session update

Revision ID: 651f577b48f8
Revises: ae4670f2fcb8
Create Date: 2023-06-11 12:48:27.348208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '651f577b48f8'
down_revision = 'ae4670f2fcb8'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_game', sa.Column('left', sa.Boolean(), nullable=True))
    op.add_column('session', sa.Column('closed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'closed')
    op.drop_column('player_game', 'left')
    # ### end Alembic commands ###
