"""game new attributes

Revision ID: 67aaadf4595c
Revises: 0a289fde0964
Create Date: 2023-06-09 23:28:45.168896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67aaadf4595c'
down_revision = '0a289fde0964'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_game', sa.Column('pawn', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_game', 'pawn')
    # ### end Alembic commands ###
