"""session attributes

Revision ID: bf29829ad173
Revises: 67aaadf4595c
Create Date: 2023-06-11 10:53:21.464222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf29829ad173'
down_revision = '67aaadf4595c'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('session_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'game', 'session', ['session_id'], ['id'])
    op.add_column('player_game', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_game', 'id')
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_column('game', 'session_id')
    # ### end Alembic commands ###
