"""room not unique

Revision ID: f282ddbde2a8
Revises: 651f577b48f8
Create Date: 2023-06-11 13:40:37.662751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f282ddbde2a8'
down_revision = '651f577b48f8'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('game_room_code_key', 'game', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('game_room_code_key', 'game', ['room_code'])
    # ### end Alembic commands ###
